spring.application.name=Ejer12

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7tk9d37uimc738sfm70-a.oregon-postgres.render.com:5432/loghub_wbxx
spring.datasource.username=loghub_wbxx_user
spring.datasource.password=AfOmHB5Lf683jimd5tqHjAl74yb1sWm6
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8081

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.password=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration